name: Cypress Test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: adopet_dev
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432

      adopet-api:
        image: jeffersonps/adopet-api:latest
        options: --name adopet-api
        env:
          NODE_ENV: development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: adopet_dev
          POSTGRES_HOST: db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test docker
        run: docker ps

      - name: Sequelize
        run: docker exec adopet-api npx sequelize-cli db:migrate

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
