name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - develop/*
      - staging/*
  push:
    branches: feature/github-actions

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.60-1-ff-125.0.1-edge-124.0.2478.51-1
      options: --user 1001
    env:
      API_URL: "https://staging.adopet.api.sapituca.site"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: REACT_APP_DEV_API_URL="${{ env.API_URL }}" npm run build

      # report machine parameterswith t
      - run: npx cypress info
      - run: node --version
      - run: node -p 'os.cpus()'

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.12.2-chrome-124.0.6367.60-1-ff-125.0.1-edge-124.0.2478.51-1
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      # matrix:
      #   containers: [1, 2]
    env:
      API_URL: "https://staging.adopet.api.sapituca.site"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v6
        with:
          start: REACT_APP_DEV_API_URL=${{ env.API_URL }} npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/tests/ui/*
          config-file: cypress.config.js
        env:
          CYPRESS_API_URL: ${{ env.API_URL }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # overwrite commit message sent to Cypress Cloud
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          # re-enable PR comment bot
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
